export const PANEL_STATES = {
  0: {
    directive: null,
    directiveColor: null,
    checklistItems: [],
    suggestedQuestions: [],
    insightCard: null,
    rewriteCard: null,
    showFcrProgress: false,
    showCaseSummary: false,
  },
  1: {
    directive: { status: '🟡 HOLD', message: 'Gather more context before deciding.', sub: 'Baseline established — monitoring for transfer signals.', color: 'yellow' },
    checklistItems: [
      { text: 'Confirm account deactivation reason with customer', done: false },
      { text: 'Check for any prior T&S review on this case', done: false },
      { text: 'Ask if customer has contacted us before about this', done: false },
    ],
    suggestedQuestions: [],
    insightCard: { icon: '📊', title: null, body: 'Baseline established. Banned account association detected — monitoring for prior review status and evidence gaps.' },
    rewriteCard: null,
    showFcrProgress: false,
    showCaseSummary: false,
  },
  2: {
    directive: { status: '🟡 HOLD', message: 'Do not transfer yet — critical gaps detected.', sub: 'Repeat contact + no resolution on record. Gather more before deciding.', color: 'red' },
    checklistItems: [
      { text: 'Check if T&S has already reviewed this case', done: false },
      { text: 'Surface any prior resolution attempts in case notes', done: false },
      { text: 'Confirm whether customer was ever given a final answer', done: false },
    ],
    suggestedQuestions: [],
    insightCard: { icon: '⚠️', title: 'Why this matters', body: '61.5% of deactivation cases transferred to T&S result in no new action — T&S confirms what was already in the system. Check for an existing review record first.' },
    rewriteCard: null,
    showFcrProgress: false,
    showCaseSummary: false,
  },
  3: {
    directive: { status: '🟡 STOP', message: 'Check the case before transferring.', sub: 'A T&S review may already exist. Re-transferring would create a duplicate with no new outcome.', color: 'red' },
    checklistItems: [
      { text: 'Check for existing T&S review record on this case', done: false },
      { text: 'Confirm whether outcome was ever communicated to customer', done: false },
      { text: 'Verify if you can deliver the final answer directly', done: false },
    ],
    suggestedQuestions: [],
    insightCard: { icon: '⚠️', title: null, body: 'T&S reviewed and closed their review on the 8th. The outcome is documented in the system. Re-transferring will result in no new action.' },
    rewriteCard: {
      original: "Instead of: 'I'll need to pass this to Trust and Safety.'",
      suggested: "Try: 'Let me check if T&S has already reviewed this before I transfer you — I want to make sure we're not sending you somewhere that won't give you a new answer.'",
    },
    showFcrProgress: false,
    showCaseSummary: false,
  },
  4: {
    directive: { status: '🟢 RESOLVE', message: 'You have everything needed to close this in-service.', sub: 'T&S review confirmed complete. Agent has full authority to deliver final outcome directly.', color: 'green' },
    checklistItems: [
      { text: 'Existing T&S review record confirmed', done: true },
      { text: 'Communication gap identified — customer never received outcome', done: true },
      { text: 'Deliver final outcome and send policy explanation to customer', done: false, highlighted: true },
    ],
    suggestedQuestions: [],
    insightCard: { icon: '✅', title: 'FCR PATH CONFIRMED', body: 'Closing this case in-service eliminates a third redundant T&S transfer and gives the customer the clear answer they have been waiting 3 weeks for.' },
    rewriteCard: null,
    showFcrProgress: true,
    showCaseSummary: false,
  },
  5: {
    directive: { status: '✅ RESOLVED', message: 'FCR achieved. Case closed in-service.', sub: 'T&S review surfaced and acted on. Customer has final written answer. No callback required.', color: 'green' },
    checklistItems: [
      { text: 'Existing T&S review record confirmed', done: true },
      { text: 'Communication gap identified and resolved', done: true },
      { text: 'Final outcome delivered and policy explanation sent', done: true },
    ],
    suggestedQuestions: [],
    insightCard: null,
    rewriteCard: null,
    showFcrProgress: false,
    showCaseSummary: true,
  },
};
